version: '3.9'

services:

  db:
    #build:
      #context: ./requirements/mariadb
      #dockerfile: mariadb
    image: mariadb:10.3
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      #- MYSQL_DATABASE=wordpress
      - MARIADB_ROOT_PASSWORD=1234
    volumes:
      - /home/jschreye/data/mariadb:/var/lib/mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    #build: 
      #context: ./requirements/wordpress
      #dockerfile: wordpress
    image: wordpress:6.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=moi
      - WORDPRESS_DB_PASSWORD=1234
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - /home/jschreye/data/wordpress:/var/www/html
    networks:
      - app-network

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    #image: nginx:1.23.2-alpine
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      #image: nginx
    volumes:
      - /home/jschreye/data/nginx:/var/www/html
      
      #- ./requirements/nginx/conf:/usr/share/nginx/html
    networks:
      - app-network
    ports:
      - 443:443
    restart: unless-stopped
  
volumes:
  mariadb:
  wordpress:
  nginx:
  conf:

networks:
  app-network:
    driver: bridge